defaults:
  - _self_
  - workload: default
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

hydra:
  run:
    dir: ./hydra_log/${workload.model.name}/${now:%Y-%m-%d}-${now:%H-%M-%S}
