model: bert

framework: tensorflow

workflow:
 generate_data: False
 train: True
 debug: False
 checkpoint: True
 
dataset: 
 data_folder: data/bert
 format: tfrecord
 num_files_train: 500
 num_samples_per_file: 313532
 record_length: 2500


train:
 computation_time: 0.968
 total_training_steps: 5000
 
reader:
 data_loader: tensorflow
 read_threads: 8
 computation_threads: 8
 transfer_size: 262144
 batch_size: 48

checkpoint:
 steps_between_checkpoints: 1250
 model_size: 4034713312
