model: cosmoflow

framework: tensorflow

workflow:
 generate_data: False
 train: True

dataset:
 data_folder: data/cosmoflow
 num_files_train: 1024
 num_samples_per_file: 512
 record_length: 131072


reader:
 data_loader: tensorflow
 computation_threads: 8
 read_threads: 8
 batch_size: 1
 
train: 
  epochs: 4
  computation_time: 0.1
