model: dlrm

framework: pytorch

workflow:
  generate_data: False
  train: True

dataset: 
  data_folder: data/dlrm
  format: bin
  num_files_train: 1
  num_files_eval: 1
  num_samples_per_file: 4195198976
  record_length: 327680
  keep_files: True
  eval_num_samples_per_file: 89145344
  
reader: 
  data_loader: terabyte
  batch_size: 2048
  batch_size_eval: 16384
  steps_between_evals: 10240

train:
  epochs: 1
  computation_time: 0.064296

evaluation: 
  eval_time: 0.5