model: cosmoflow_pt

framework: pytorch

workflow:
 generate_data: False
 train: True

dataset:
 data_folder: data/cosmoflow_pt
 num_files_train: 524288
 num_files_eval: 65536
 num_samples_per_file: 1
 record_length: 16777488
 record_length_stdev: 0
 format: npz

reader:
 data_loader: dali
 read_threads: 4
 batch_size: 1
 
train: 
  epochs: 4
  computation_time: 0.0099
