model: dlrm

framework: pytorch

workflow:
  generate_data: False
  train: True
  do_eval: True

dataset:
  data_folder: data/dlrm
  format: indexed_binary
  num_files_train: 1
  num_files_eval: 1
  num_samples_per_file: 4195198976
  record_length: 327680
  keep_files: True
  eval_num_samples_per_file: 91681240

reader:
  data_loader: pytorch
  batch_size: 2048
  batch_size_eval: 16384
  sample_shuffle: random

train:
  epochs: 1
  computation_time: 0.064296
  total_training_steps: 32768
  total_eval_steps: 2048

evaluation:
  eval_time: 0.0843
  steps_between_evals: 16384