model: 
  name: dlrm

framework: pytorch

workflow:
  generate_data: False
  train: True
  do_eval: False

dataset:
  data_folder: data/dlrm
  format: indexed_binary
  num_files_train: 1
  num_files_eval: 1
  num_samples_per_file: 4195198976
  record_length_bytes: 327680
  keep_files: True
  eval_num_samples_per_file: 91681240

reader:
  data_loader: pytorch
  batch_size: 2048
  batch_size_eval: 16384
  sample_shuffle: random

train:
  epochs: 1
  computation_time: 0.064296
