# 8 node run with 4 GPUs per node and TPSIZE=4 and PPSIZE=8
model: 
  name: llama_405b
  type: transformer
  model_size: 30102
  num_layers: 126
  parallelism: 
    tensor: 8
    pipeline: 16
    zero_stage: 1
  transformer: 
    vocab_size: 128000
    hidden_size: 16384
    ffn_hidden_size: 53248

framework: pytorch

workflow:
  generate_data: True
  train: True
  checkpoint: True

dataset: 
  data_folder: data/llama_405b/
  format: mmap_indexed_binary
  num_files_train: 1
  num_samples_per_file: 1048576
  record_length: 2048
  
reader: 
  data_loader: pytorch
  batch_size: 16
  read_threads: 1
  file_shuffle: seed
  sample_shuffle: seed

train:
  epochs: 3
  computation_time: 5 # 2.44 sec per step
  total_training_steps: 5

checkpoint:
  checkpoint_folder: checkpoints/llama_405b
  steps_between_checkpoints: 1
  model_datatype: fp16
  optimizer_datatype: fp32
