model: unet3d

framework: pytorch

workflow:
  generate_data: False
  train: True
  checkpoint: True

dataset: 
  data_folder: data/megatron-deepspeed/
  format: mmap_indexed_binary
  num_files_train: 1
  num_samples_per_file: 277203535
  record_length: 4096
  
reader: 
  data_loader: pytorch
  batch_size: 1024
  read_threads: 8
  file_shuffle: seed
  sample_shuffle: seed

train:
  epochs: 311541
  computation_time: 8.99

checkpoint:
  checkpoint_folder: checkpoints/megatron-deepspeed
  checkpoint_after_epoch: 1000
  model_size: 30102
  optimization_groups: [1009254400, 865075200, 793600]
  num_layers: 44
  layer_parameters: [129761280, 20971520]
