model: resnet50

framework: pytorch

workflow:
 generate_data: False
 train: True

dataset:
 num_files_train: 1024
 num_samples_per_file: 1251
 record_length: 114660.07
 record_length_resize: 150528
 data_folder: data/resnet50
 format: tfrecord

train: 
 computation_time: 0.224
 epochs: 5
 
reader:
 data_loader: dali
 read_threads: 8
 computation_threads: 8
 batch_size: 400
 dont_use_mmap: True